### ISSUE TITLE
Hostname not shown in V 21.02.0

### ISSUE THREAD

**Issue by DittelHome** [openwrt/luci#5368] opened 2021-09-16 16:57 UTC
Hi,
i get only hostnames for IPV4 devices. 
For devices which are able to handle IPV6 and IPV4 resolving is not working. 
In 19.07.* releases i got always the correct hostname. 
Hostnames entries filled correct.

![assoiciated_LI](https://user-images.githubusercontent.com/14176684/133653244-9138a3c6-5c80-402f-be3e-1b3a9ea05f3a.jpg)
![hostnames](https://user-images.githubusercontent.com/14176684/133653224-ae34d10e-581b-4edc-865d-f5560905d534.PNG)

**Comment by DittelHome** [comment] 2021-09-20 15:00
Same Problem, different description.... #5206

**Comment by jow-** [comment] 2021-09-22 10:55
Dupe of #5206

**Closed by jow-** 2021-09-22 10:55 UTC
