### ISSUE TITLE
admin/system/opkg: Sorting by size sorts alphabetically

### ISSUE THREAD

**Issue by tvogel** [openwrt/luci#6120] opened 2022-11-28 23:05 UTC
## Steps to reproduce:

1. go to: System → Software → Installed tab
2. Click on "Size (.ipk)" column header

## Actual behavior:
Sorts by alphabet, i.e. you'll find sections like this:

Package name | Version | Size (.ipk) | Description | &nbsp;
-- | -- | -- | -- | --
...
kmod-nf-conntrack6 | 5.10.146-1 | ~846 B | Netfilter IPv6 connection tracking | Remove…
jsonfilter | 2018-02-04-c7e938d6-1 | ~9.0 KB | OpenWrt JSON filter utility | Remove…
kmod-crypto-rng | 5.10.146-1 | ~9.3 KB | CryptoAPI random number generation | Remove…
kmod-usb2 | 5.10.146-1 | ~9.6 KB | Kernel support for USB2 (EHCI) controllers | Remove…
kmod-crypto-null | 5.10.146-1 | ~940 B | Null CryptoAPI module | Remove…
...

## Expected behavior:
The unit suffix is taken into account and sorting is done by the real size.

## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`

**Example: Replace the following lines and remove this**
```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='22.03.2'
DISTRIB_REVISION='r19803-9a599fee93'
DISTRIB_TARGET='ath79/generic'
DISTRIB_ARCH='mips_24kc'
DISTRIB_DESCRIPTION='OpenWrt 22.03.2 r19803-9a599fee93'
DISTRIB_TAINTS=''
```

**Comment by jow-** [comment] 2022-11-29 11:40
Duplicate of #5994 - same root cause/functionality

**Closed by jow-** 2022-11-29 11:40 UTC
