### ISSUE TITLE
Apostrophe (UTF-8: &#39;) shows as code instead of character in luci using french translation

### ISSUE THREAD

**Issue by viking76** [openwrt/luci#2621] opened 2019-03-13 08:42 UTC
OpenWrt 18.06.2 r7676-cddd7b4c77 / LuCI openwrt-18.06 branch (git-19.020.41695-6f6641d) 
The problem was not been resolved by the back issue
the good special character is   '     "Vue d'ensemble"

![bugluci](https://user-images.githubusercontent.com/130782/54264692-f2e28d80-4573-11e9-82da-e63d7b02690f.jpg)

**Comment by viking76** [comment] 2019-03-13 09:03
I have updated with last update. view in the code html its not true 

![bugluci2](https://user-images.githubusercontent.com/130782/54266067-ed3a7700-4576-11e9-8bb5-efc915edc412.png)

**Comment by jow-** [comment] 2019-03-13 10:28
Dupe of #1410.

**Comment by viking76** [comment] 2019-03-13 10:28
I would be a theme problems  it work well on openwrt theme and freifunk-theme

**Closed by jow-** 2019-03-13 10:28 UTC
