### ISSUE TITLE
luci-app-openvpn - VPN Tab Settings Missing

### ISSUE THREAD

**Issue by Presjar** [openwrt/luci#887] opened 2016-12-18 12:59 UTC
When using luci-> Services -> OpenVPN -> Switch to advanced configuration -> Tab 'VPN' 
On click, the window shows all the expected settings for a split second and then changes to show only 'client' tickbox Configure client mode.

luci-app-openvpn git-16.352.65143-1741e55-1
LEDE Reboot SNAPSHOT r2524-aada15a / LuCI Master (git-16.352.65143-1741e55)

**Comment by paulbalomiri** [comment] 2017-01-03 07:28
Hello, i can confirm the same problem (with briefly appearing option ) in luci-app-openvpn - git-16.018.33482-3201903-1

**Comment by Wedmer** [comment] 2017-04-25 16:25
The problem is in filter options. Filter wants variable server_mode="1" to show those options, but there're no such variable. Later there will be fix for this.

**Closed** 2017-04-25 17:14 UTC
Labels: help wanted
