### ISSUE TITLE
Unspecified 'Firewall Zone' Bug

### ISSUE THREAD

**Issue by ahmar20** [openwrt/luci#2452] opened 2019-01-12 09:39 UTC
I am seeing this issue for quite some time now.  The issue is when you create an interface in Network->Interfaces but you dont assign it a Firewall zone (it is marked 'unspecified' in LuCI as default) and you hit Save&Apply it actually creates a new firewall zone named '1'. Even if you dont hit Save&Apply and just hit Save, you can see the above behavior by navigating to Pending Changes screen and look for the changes that will be applied. 

I also created a forum thread for this issue. This is just not related to Firewall, it kind of exists on every network related config where you can specify the Firewall zone manually or can choose a network zone manually. Whether it's Dropbear, Firewall Input/output Rules or Interfaces.
It is surely a bug, maybe just for Lantiq based devices. I have tested it with 2 devices, Tp-Link TD-W8980 and BT HomeHub 5A, running v18.06.1. Tested with luci-theme-bootstrap, luci-theme-material and luci-theme-rosy.

More info and pictures in Post 3: https://forum.openwrt.org/t/bug-in-dropbear-luci/28165/3

**Comment by jow-** [comment] 2019-01-13 13:16
Dupe of #2224

**Closed by jow-** 2019-01-13 13:16 UTC
