### ISSUE TITLE
luci-mod-status and luci-base: Luci Web UI stuck at Loading view after latest update

### ISSUE THREAD

**Issue by fab4x** [openwrt/luci#6233] opened 2023-02-09 10:34 UTC
Yesterday I installed two Updates for my OpenWrt Router (luci-mod-status and luci-base) and now I can't access the Web Ui anymore. I already tried to reinstall luci but it didn't fix the problem. It just says "**Loading view...**". 
The Console log gives out the following error:

`luci.js?v=git-23.038.39289-18dde0c:155 Uncaught (in promise) SyntaxError: Unexpected identifier 'frameEl'
  in https://192.168.200.1/luci-static/resources/ui.js?v=git-23.038.39289-18dde0c:?
  at luci.js?v=git-23.038.39289-18dde0c:179:29
    at Object.raise (luci.js?v=git-23.038.39289-18dde0c:155:3)
    at luci.js?v=git-23.038.39289-18dde0c:179:29
luci.js?v=git-23.038.39289-18dde0c:163 Uncaught (in promise) TypeError: classes.ui.addNotification is not a function
    at error (luci.js?v=git-23.038.39289-18dde0c:163:12)`

Did anyone else experienced the same?

Additional Infos about my Router:
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='22.03.0'
DISTRIB_REVISION='r19685-512e76967f'
DISTRIB_TARGET='ipq40xx/generic'
DISTRIB_ARCH='arm_cortex-a7_neon-vfpv4'
DISTRIB_DESCRIPTION='OpenWrt 22.03.0 r19685-512e76967f'
DISTRIB_TAINTS=''

**Comment by minax007** [comment] 2023-02-09 10:59
I have experienced the same with the latest snapshot build on an Asrock G10 (ipq806).

**Comment by jow-** [comment] 2023-02-09 11:20
Duplicate of https://github.com/openwrt/luci/issues/6230

**Closed by jow-** 2023-02-09 11:20 UTC
