### ISSUE TITLE
username and password different from factory

### ISSUE THREAD

**Issue by rctito55** [openwrt/luci#3177] opened 2019-10-13 15:17 UTC
after resetting the mini router, when writing user: root and password: admin I get "Invalid username and / or password! Please try again." Could someone help me? This forum may not be for that but I can't find a way out of the problem. Thanks in advance

**Comment by ysc3839** [comment] 2019-10-13 15:24
By default root password is empty. Just click the login button.
Or are you using some modded firmware?

**Comment by rctito55** [comment] 2019-10-13 15:34
It is likely that the firmware was modified because, after factory reset, it comes out in ip 192.168.8.1, instead of 192.168.1.1 as in the user manual. Try these user and pass and it is none:
admin admin, root root, 1234 1234, its combinations and also root and without password and it is not ... any suggestion is welcome

**Comment by rctito55** [comment] 2019-10-13 15:36
Only the default user that is root is maintained, as a suggestion, in the textbox. If there is any way to return the factory firmware it would be very important to know

**Comment by hnyman** [comment] 2019-10-13 16:17
> after factory reset, it comes out in ip 192.168.8.1, instead of 192.168.1.1 as in the user manual. Try these user and pass and it is none: admin admin, root root, 1234 1234, its combinations and also root and without password and it is not ... any suggestion is welcome

You might try using the failsafe mode. It can be triggered in the early boot process and it enables you to enter the ssh console without password. (just the username root, if asked)
https://openwrt.org/docs/guide-user/troubleshooting/failsafe_and_factory_reset#failsafe_mode 

(note that entering the failsafe mode requires you to press a button on the router during a specific two-second time window during the boot process. The exact moment depends on the router.

But as your issue has nothing to do with LuCI GUI and is not a bug, I close this issue.

**Closed by hnyman** 2019-10-13 16:17 UTC
