### ISSUE TITLE
<luci>: Generate archive produces empty file

### ISSUE THREAD

**Issue by tones111** [openwrt/luci#6961] opened 2024-03-04 02:06 UTC
I installed snapshot r25381 onto a DL-WRX36 and installed the luci and luci-ssl packages.  When browsing to the System->Backup/Flash Firmware page and selecting the "Generate archive" button the file that's saved to my computer is empty (0 bytes).  This happens regardless of destination location (home dir, /tmp, etc).

According to [this forum post](https://forum.openwrt.org/t/generate-archive-gives-empty-config-backup-file/190096/2) another user is seeing the same issue since snapshot r25361 on GL-MT6000 and E8450.

## Expected behavior:
A valid tar archive containing the device's config files is saved.  This file can be used to restore the device's configuration.

## Additional Information:
I don't see any error messages in dmesg.  The system log only says
```
Sun Mar  3 19:41:41 2024 user.info upgrade: Saving config files...
Sun Mar  3 19:42:20 2024 user.info upgrade: Saving config files...
Sun Mar  3 19:42:42 2024 user.info upgrade: Saving config files...
```

```
# cat /etc/openwrt_release
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r25381-336a531c15'
DISTRIB_TARGET='qualcommax/ipq807x'
DISTRIB_ARCH='aarch64_cortex-a53'
DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r25381-336a531c15'
DISTRIB_TAINTS=''
```

**Comment by jow-** [comment] 2024-03-04 13:57
Duplicate of https://github.com/openwrt/openwrt/issues/14773

**Closed by jow-** 2024-03-04 13:57 UTC
