### ISSUE TITLE
luci: doesn't work

### ISSUE THREAD

**Issue by castillofrancodamian** [openwrt/luci#6231] opened 2023-02-08 16:57 UTC
Hi @jow- 

root@archer_c60:~# cat /etc/openwrt_release
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r22020-1c31ca5da9'
DISTRIB_TARGET='ath79/generic'
DISTRIB_ARCH='mips_24kc'
DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r22020-1c31ca5da9'
DISTRIB_TAINTS='no-all busybox'

**Comment by castillofrancodamian** [comment] 2023-02-08 16:57
![Screenshot_20230208_135452](https://user-images.githubusercontent.com/47670442/217598879-f767934f-cf6a-4153-96fd-f7108592d647.png)

**Comment by hnyman** [comment] 2023-02-08 17:12
Duplicate of #6230

Likely already fixed by 41e9b8d1

**Closed by hnyman** 2023-02-08 17:12 UTC
