### ISSUE TITLE
Alignment issue if one interface is disabled on wireless overview page

### ISSUE THREAD

**Issue by weyou** [openwrt/luci#2941] opened 2019-08-01 09:46 UTC
A picture is worth a thousand words.

![image](https://user-images.githubusercontent.com/5524708/62283454-2a4ec980-b484-11e9-9495-0a8c4f779fa1.png)

This issue happens on Chrome/Firefox/IE/Edge.

**Comment by jow-** [comment] 2019-08-01 10:03
Dupe of #2388

**Closed by jow-** 2019-08-01 10:03 UTC
