### ISSUE TITLE
luci-app-dockerman: overview unhandled nil

### ISSUE THREAD

**Issue by PovilasID** [openwrt/luci#6308] opened 2023-03-24 17:52 UTC
## Steps to reproduce:
**Example: Replace the following lines and remove this**

1. After fresh install
2. go to: Docker → Overview 

## Actual behavior:
 
Error is thrown :
```
Runtime error
Unhandled exception during request dispatching
/usr/lib/lua/luci/ucodebridge.lua:23: /usr/lib/lua/luci/model/cbi/dockerman/overview.lua:68: bad argument #1 to 'ipairs' (table expected, got nil)

In error(), file [C]
called from function [anonymous function] (/usr/lib/lua/luci/ucodebridge.lua:23)
called from function ((tail call))
In [anonymous function](), file /usr/share/ucode/luci/runtime.uc, line 148, byte 45:
  called from function [arrow function] (/usr/share/ucode/luci/dispatcher.uc:794:4)
  called from function render ([C])
  called from function render_action (/usr/share/ucode/luci/dispatcher.uc:768:24)
  called from function run_action (/usr/share/ucode/luci/dispatcher.uc:795:4)
  called from function [anonymous function] (/usr/share/ucode/luci/dispatcher.uc:998:48)
  called from anonymous function (/www/cgi-bin/luci:39:12)

 `        return lcall.call(modname, method, ...args);`
  Near here ----------------------------------------^
```

## Expected behavior:

 Some kind of ui overview

## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`

```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r22372-f7c1631155'
DISTRIB_TARGET='x86/64'
DISTRIB_ARCH='x86_64'
DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r22372-f7c1631155'
DISTRIB_TAINTS=''
```

**Comment by jow-** [comment] 2023-03-24 19:22
Duplicate of #6300

**Closed by jow-** 2023-03-24 19:22 UTC

**Comment by cyqtmxk** [comment] 2023-04-10 02:05
+1
