### ISSUE TITLE
Linksys WRT1900ACS imagebuilder VPN on status bar

### ISSUE THREAD

**Issue by pesa1234** [openwrt/luci#4066] opened 2020-05-18 12:18 UTC
Dear guys, I have just installed the 19.07.3 version on my router and I can not find on top bar VPN, I have installed luci-app-openvpn git-20.138.63234-ccd9d67-1 and luci-app-vpnbypass git-20.138.63234-ccd9d67-19.

![Istantanea_2020-05-18_14-17-37](https://user-images.githubusercontent.com/6216993/82212186-6cad9e00-9912-11ea-9b16-35717d44bfe3.png)

**Comment by jow-** [comment] 2020-05-19 10:44
The issue is caused by `luci-app-vpnbypass`. Should be addressed by ecd49247eb7d319b8345837246b14f47acc6de94, 7f4de85b0b9c4f6bd9a19bf5a44af3825b31e8c1 and 4dcab51ca522407cf63a51883bc6505cf24fbd64 once updated packages are built.

**Closed by jow-** 2020-05-19 10:44 UTC
