### ISSUE TITLE
DOMException: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL

### ISSUE THREAD

**Issue by olekstomek** [openwrt/luci#5507] opened 2021-11-10 22:38 UTC
When I login to LuCI I have page without information:
![image](https://user-images.githubusercontent.com/26818304/141204399-ebffea52-4c1c-4ccf-bff6-40c2dd104ce3.png)

On console I see:

> {
>     "stack": "Error: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL\n    at http://192.168.1.1/luci-static/resources/luci.js?v=git-21.301.66596-f28aaa3:53:9\n    at new Promise (<anonymous>)\n    at ClassConstructor.request (http://192.168.1.1/luci-static/resources/luci.js?v=git-21.301.66596-f28aaa3:47:283)\n    at flushRequestQueue (http://192.168.1.1/luci-static/resources/luci.js?v=git-21.301.66596-f28aaa3:39:31)"
> }

After refreshing the page, data loads properly. The problem almost always occurs - I think I can say 8 out of 10 times the problem occurs.

I use Google Chrome 95.0.4638.69 (Official version) (64-bits), I was checking in incognito mode also - problem is the same. 
On Microsoft EDGE - the same.

Powered by LuCI openwrt-21.02 branch (git-21.301.66596-f28aaa3) / OpenWrt 21.02.1 r16325-88151b8303

**Comment by jow-** [comment] 2021-12-03 23:50
Duplicate of #3747

**Closed by jow-** 2021-12-03 23:50 UTC
