### ISSUE TITLE
Can't choose to IPv6 in diagnostics.

### ISSUE THREAD

**Issue by Karmylr** [openwrt/luci#6421] opened 2023-06-07 16:14 UTC
### Describe the bug

When I clicked the drop-down arrow next to the `IPv4 Ping` button, only a horizontal line appeared

### OpenWrt version

r23040-ec6bbc5255

### OpenWrt target/subtarget

x86/64

### Device

J4125,VMware ESXi

### Image kind

Self-built image

### Steps to reproduce

Go to diagnostics and try to choose to IPv6 Ping.

### Actual behaviour

A line appears

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by jow-** [comment] 2023-06-07 21:02
Duplicate of #6379

**Closed by jow-** 2023-06-07 21:02 UTC

**Comment by Karmylr** [comment] 2023-06-09 03:07
After git pull and rebuild, there is still this problem.

**Comment by Karmylr** [comment] 2023-06-11 03:27
@jow- After git pull and rebuild, there is still this problem.
