### ISSUE TITLE
luci-theme-openwrt-2020The updated interface is very cluttered！The fallback display is normal！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [openwrt/luci#4917] opened 2021-03-13 13:04 UTC
**The updated interface is very cluttered：**
![image](https://user-images.githubusercontent.com/45259624/111030873-930f6d80-843f-11eb-89fd-5ffb46873df0.png)
**The fallback display is normal：**
![image](https://user-images.githubusercontent.com/45259624/111030891-ade1e200-843f-11eb-9e97-4c46224db99c.png)

**Comment by hnyman** [comment] 2021-03-13 13:10
Duplicate of #4916

You have a modified non-standard overview page. 
You should discuss it with the author of your build, as the default luci-theme-openwrt-2020 does not look like that.

**Closed by hnyman** 2021-03-13 13:10 UTC
