### ISSUE TITLE
luci Hangs On Loading View Using Latest Snapshot

### ISSUE THREAD

**Issue by khanjui** [openwrt/luci#6236] opened 2023-02-10 08:48 UTC
luci

Steps to reproduce:
Go to 192.168.1.1

Actual behavior:
Infinite "loading view" screen. Same on bootstrap theme. I tried factory reset but it didn't change anything.

![image](https://user-images.githubusercontent.com/17529452/218045784-d15ba150-f28c-46a6-b8ed-541670bef07e.png)

Expected behavior:
Should work fine.

Additional Information:
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r22036-1a145ccb0a'
DISTRIB_TARGET='lantiq/xrx200'
DISTRIB_ARCH='mips_24kc'
DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r22036-1a145ccb0a'
DISTRIB_TAINTS=''

**Comment by jow-** [comment] 2023-02-10 09:19
Duplicate of https://github.com/openwrt/luci/issues/6230

**Closed by jow-** 2023-02-10 09:19 UTC
