### ISSUE TITLE
luci-app-openvpn: Dependency on `openvpn` missing in 23.05.0-rc3.

### ISSUE THREAD

**Issue by dreirund** [openwrt/luci#6564] opened 2023-09-04 15:36 UTC
In OpenWRT 23.05.0-rc3, the package `luci-app-openvpn` misses dependencies on `openvpn`:

Installing just `luci-app-openvpn` gives a Luci-interface for OpenVPN, but fails to actually start it because openvpn is missing.

**Comment by jow-** [comment] 2023-09-05 06:26
Duplicate of #5949

**Closed by jow-** 2023-09-05 06:26 UTC
