### ISSUE TITLE
Switch menu item missing if no switch configuration exists

### ISSUE THREAD

**Issue by courtarro** [openwrt/luci#1901] opened 2018-06-21 20:21 UTC
I installed a fresh copy of LEDE 17.01.4 on a Netgear WNR3500L. The default configuration on this router has no switch settings, and as a result, the Switch menu item in LuCI is missing. I was able to get this menu item to appear by following a workaround on #646. It seems like a bug that the Switch interface is missing unless one already exists.

**Comment by jow-** [comment] 2018-07-02 07:37
This is by design. If no suitable switch configuration is present by default, this is a bug that needs to be addressed in OpenWrt directly.

**Closed by jow-** 2018-07-02 07:37 UTC
