### ISSUE TITLE
Luci login screen shows menu entries when using unofficial packages.

### ISSUE THREAD

**Issue by hudra0** [openwrt/luci#6110] opened 2022-11-20 15:34 UTC
## Steps to reproduce:

1. Build custom image with unofficial luci-app-diskman package.
2. flash image
3. login screen looks like this
![image](https://user-images.githubusercontent.com/117863474/202910700-829d2aa0-6d70-4c91-8371-3feb813e15b4.png)

## Expected behavior:

```
There should be no menu visible. This was working until a few builds. Probably until the end of october.
```

## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`

```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r21326-bca663f20f'
DISTRIB_TARGET='x86/64'
DISTRIB_ARCH='x86_64'
DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r21326-bca663f20f'
DISTRIB_TAINTS='no-all override'
```

**Comment by jow-** [comment] 2022-11-20 21:46
Looks like a duplicate of / caused by https://github.com/openwrt/luci/issues/6105

**Closed by jow-** 2022-11-20 21:46 UTC

**Comment by hudra0** [comment] 2022-11-20 21:56
Thanks for looking into it. Just for your information: this issue wasn't argon theme specific.. also happens with other themes.
