### ISSUE TITLE
Inconsistent handling of static DHCP leases with multiple MAC addresses

### ISSUE THREAD

**Issue by ktetzlaff** [openwrt/luci#5176] opened 2021-07-08 03:32 UTC
The following problem report is for a Turris Omnia with SW version 5.2.2 which is based on OpenWRT 19.07.x (`/etc/openwrt_version`: `ec76c365c1d60bf6a4f69b1ab3ce132f97f34dbb`, `Powered by LuCI branch (git-21.160.68865-15ca915)`).

When entering data for a static DHCP lease, there is the option to provide multiple MAC addresses (according to the dnsmasq docs, this can be used to assign a fixed IP to e.g. a laptop with ETH and WiFi interfaces). The documentation (https://openwrt.org/docs/guide-user/base-system/dhcp) says:

```
mac | string | no | (none) | The hardware address(es) of this host, separated by spaces.
```

and this is also how LuCI allows to specify the MAC addresses (in the `Edit` dialog of static leases). However, when such an entry is saved, LuCI apparently cannot handle it properly. In the overview of `Static Leases` on the `DHCP and DNS` page, the MAC addresses then just show up as `none` (or `unspecified` in the `Edit` dialog).

LuCI saves the entry in `/etc/config/dhcp` as:

```
config host
        ...
        option mac '01:02:03:04:05:06 11:12:13:14:15:16'
        ...
```

If this is manually converted from the space separated string representation to a list, like:

```
config host
        ...
        list mac '01:02:03:04:05:06'
        list mac '11:12:13:14:15:16'
        ...
```

both MAC addresses are displayed properly in the Web UI (in the overview and in the `Edit` dialog). Also, the resulting dnsmasq config is the same for both variants.

In case this hasn't been fixed in a more recent LuCI/OpenWRT release the question is, which variant is correct? Either the documentation and the `Edit/Save`  code are right and the display code needs to be updated or the display code is correct and the documentation and `Edit/Save` need fixing.

**Comment by jow-** [comment] 2021-07-08 06:27
Duplicate of #4291, fixed via 7b931da4779c68f5aef5908286c2ae5283d2dece

**Closed by jow-** 2021-07-08 06:27 UTC
