### ISSUE TITLE
nslookup error message (busybox-musl incompatibility)

### ISSUE THREAD

**Issue by psyborg55** [openwrt/luci#991] opened 2017-02-05 03:36 UTC
when trying to do nslookup luci return this message: nslookup: can't resolve '(null)': Name does not resolve
 but the address is resolved successfully:

Name:      openwrt.org
Address 1: 78.24.191.177 openwrt.org

happens in both r50082 and LEDE 17.01.0-rc1

might be related to something in this ticket: https://dev.openwrt.org/ticket/11495

**Comment by hnyman** [comment] 2017-02-05 08:14
I will close this, as this is not an LuCI issue.  Luci uses nslookup app from busybox for the lookup here.

The busybox nslookup is still somewhat incompatible with musl. The server argument is ignored, and if no server is given on cmd line, this error is printed.

The issue is discussed and tracked at least in
https://dev.openwrt.org/ticket/20893
https://dev.openwrt.org/ticket/18333
(also https://dev.openwrt.org/ticket/11495 was hijacked later for this issue)
https://bugs.lede-project.org/index.php?do=details&task_id=155

Likely the fix should be done in busybox source code. (The musl developers know about the problem but as they think that the fault is on busybox side thay are not changing musl: http://lists.busybox.net/pipermail/busybox/2014-November/081960.html )

**Closed by hnyman** 2017-02-05 08:14 UTC
