### ISSUE TITLE
NullRef if luci.config.sauth.sessiontime not set 

### ISSUE THREAD

**Issue by SamJongenelen** [openwrt/luci#576] opened 2015-12-15 20:19 UTC
in [luci-mod-rpc issue](https://github.com/openwrt/luci/blob/69fd4f14eef783076b69315c71fe57baad1f8925/modules/luci-mod-rpc/luasrc/controller/rpc.lua#L55) `luci.config.sauth.sessiontime`
 line # 55 is not set

This causes [this issue](https://github.com/openwrt/luci/issues/427)  (which had been closed, but still wanted to link it for the cause) and my issue [over here](https://github.com/balloob/home-assistant/issues/753)

Can someone please make a nullcheck / array check? I can't seem to get luci running in my visual studio

**Comment by jow-** [comment] 2015-12-15 22:34
I cannot reproduce the problem, that variable is provided indirectly by the "luci.config" module which maps /etc/config/luci as proxy table into the block scope.

What LuCI version did you use exactly when you encountered the problem?

**Comment by jow-** [comment] 2015-12-15 22:40
Nevermind, I see that revision 3836b45 was mentioned in the other report.
The issue described here has already been fixed with fff7c6c5188ff7a82b5d9f46a6f2c143288b5ed1.

**Closed by jow-** 2015-12-15 22:40 UTC

**Comment by jow-** [comment] 2015-12-15 22:45
I also cherry-picked fff7c6c5188ff7a82b5d9f46a6f2c143288b5ed1 into the `for-15.05` branch now.

**Comment by SamJongenelen** [comment] 2015-12-16 09:08
Excellent I'll pull the update tonight thanks

**Comment by cctv838126** [comment] 2018-03-17 11:27
my router is Lenovo newifi mini，i use “opkg install rpcd-mod-file -nodeps“” install the rpcd-mod-file，And create a read-only user to be used by setting up the ACL file /usr/share/rpcd/acl.d/user.json，restart the services，but the “ubus list | grep file” give no return。the homeasisstant gives no error，nether i can not find the device in the “history”。

**Comment by marine1988** [comment] 2018-11-20 22:29
I cant conect my openwrt tp with homeassistant

**Comment by flipreverse** [comment] 2019-01-26 10:43
Believe it or not: This issue is still present in OpenWRT r9136-f4d6e8f98f.
I do not see why fff7c6c is a fix to this. Why does a "require .." make things better?

**Comment by cagnulein** [comment] 2020-09-07 12:26
> Believe it or not: This issue is still present in OpenWRT r9136-f4d6e8f98f.
> I do not see why [fff7c6c](https://github.com/openwrt/luci/commit/fff7c6c5188ff7a82b5d9f46a6f2c143288b5ed1) is a fix to this. Why does a "require .." make things better?

did you fix it in some way?
