### ISSUE TITLE
Problem firewall

### ISSUE THREAD

**Issue by fiduchi** [openwrt/luci#4944] opened 2021-03-25 20:27 UTC
Problem. In firewoll, when creating a parental control rule for mak time limits, when you check the box and click the save and apply button, the checkbox is removed.

**Comment by fiduchi** [comment] 2021-03-25 20:28
Firewall

**Comment by stangri** [comment] 2021-03-25 21:01
Seems to be a duplicate of https://github.com/openwrt/luci/issues/4938.

**Closed by stangri** 2021-03-25 21:01 UTC
