### ISSUE TITLE
Luci 21.02 Crashes while viewing connections with graphs

### ISSUE THREAD

**Issue by c0ke543** [openwrt/luci#5181] opened 2021-07-11 16:24 UTC
Running namebench with default 150 connection limit causes luci to crash if viewing the realtime graph for DNS connections. The crash occurs at about 500 connections being open with the settings above. The Chart will freeze. This indicates the crash occurred. You can navigate around to confirm the crash. Nothing will load or error messages be displayed. Previous versions on 19.07 would hang / slow but not crash once in the thousands 4-5k+. Under 1500 wasn't a problem. It will not crash if just viewing the status page. Once luci crashes, it's inoperable until CLI reboot or a service restart on uhttpd. 

The router still functions only the GUI crashes it seems.

Router WRT1900ACS v2

LuCI openwrt-21.02 branch (git-21.188.55099-e52e1de)
OpenWrt 21.02.0-rc3 r16172-2aba3e9784

Example of errors thrown post crash:

RPCError
RPC call to luci/getInitList failed with error -32000: Object not found
  at ClassConstructor.handleCallReply (http://192.168.1.1/luci-static/resources/rpc.js?v=git-21.188.55099-e52e1de:11:3)

**Comment by jow-** [comment] 2021-07-11 17:06
Dupe of #4816

**Closed by jow-** 2021-07-11 17:06 UTC
