### ISSUE TITLE
luci-protocol-qmi: no ip address shown under the Interfaces menu

### ISSUE THREAD

**Issue by dchard** [openwrt/luci#1773] opened 2018-04-30 22:18 UTC
Dear deleopers,

I am using a Quectel EC25 modem with latest trunk for ar71xx GL-MIFI device, and noticed that if the modem is in QMI mode, the Interfaces menu is not showing the IP address of the connection:

![qmi_luci_no_ip](https://user-images.githubusercontent.com/8152156/39453004-9d61618a-4cd4-11e8-9905-a5b994682c6a.png)

The connection itsefl is working, there is traffic, but no IP address.

On the status page the same connection reports IP data correctly:

![qmi_luci_status](https://user-images.githubusercontent.com/8152156/39453089-eab79aa8-4cd4-11e8-9050-154fc14ac825.png)

The modem also reports IP connectivity with ifconfig and uqmi as well.

OpenWrt SNAPSHOT r6781-2c192b6 / LuCI Master (git-18.100.52589-d42ce28)
Kernel: 4.9.96

**Comment by jow-** [comment] 2018-05-02 14:36
Dupe of #1683

**Closed by jow-** 2018-05-02 14:36 UTC
