### ISSUE TITLE
QSM QOS luci app has just a little issue

### ISSUE THREAD

**Issue by desigabri** [openwrt/luci#4494] opened 2020-10-05 19:32 UTC
H, I'll be very fast:

I just to advise you that  this luci package has **inverted** input fields for 
Download speed  and Upload speed , there is the need to  invert the fields or the description in the main page

nice app thanks

**Comment by hnyman** [comment] 2020-10-05 20:05
Duplicate of #4493

**Closed by hnyman** 2020-10-05 20:05 UTC

**Comment by desigabri** [comment] 2020-10-05 23:43
damn!!! my fault! :( :( :(

I setted eth1 in place of eth0.2 for the Internet interface, so the
controller worked by watching the br.lan so the Download and Upload were
up-down  :(

sorry and thanks

Il giorno lun 5 ott 2020 alle ore 22:05 Hannu Nyman <
notifications@github.com> ha scritto:
