### ISSUE TITLE
lucihttp has a bug？

### ISSUE THREAD

**Issue by osdu** [openwrt/luci#2751] opened 2019-06-05 06:38 UTC
If the textarea has multiple lines and the last line is not a blank line but a single character, the textarea value will not be obtained.

https://github.com/jow-/lucihttp/issues/2

https://github.com/openwrt/luci/issues/2737

**Comment by jow-** [comment] 2019-06-05 07:21
Duplicate of https://github.com/jow-/lucihttp/issues/2

**Closed by jow-** 2019-06-05 07:21 UTC
