### ISSUE TITLE
snapshot version luci stuck at "Loading view..."

### ISSUE THREAD

**Issue by chinabb** [openwrt/luci#6232] opened 2023-02-09 02:12 UTC
## Steps to reproduce:
Use the Chrome browser to access the router web interface, and the luci interface is stuck and a message "Loading view..." appears at any page I navigate and then hangs indefinitely.

## Actual behavior:

Chrome  F12 show errors:
GET http://192.168.1.1/cgi-bin/luci/ 403 (Forbidden)
luci.js?v=git-23.038.47117-2234d0c:161 SyntaxError: Unexpected identifier 'frameEl' (at luci.js?v=git-23.038.47117-2234d0c:155:3)
  in http://192.168.1.1/luci-static/resources/ui.js?v=git-23.038.47117-2234d0c:?
  at luci.js?v=git-23.038.47117-2234d0c:179:29
    at Object.raise (luci.js?v=git-23.038.47117-2234d0c:155:3)
    at luci.js?v=git-23.038.47117-2234d0c:179:29
luci.js?v=git-23.038.47117-2234d0c:161 SyntaxError: Unexpected identifier 'frameEl' (at luci.js?v=git-23.038.47117-2234d0c:155:3)
  in http://192.168.1.1/luci-static/resources/ui.js?v=git-23.038.47117-2234d0c:?
  at luci.js?v=git-23.038.47117-2234d0c:179:29
    at Object.raise (luci.js?v=git-23.038.47117-2234d0c:155:3)
    at luci.js?v=git-23.038.47117-2234d0c:179:29
luci.js?v=git-23.038.47117-2234d0c:155 Uncaught (in promise) SyntaxError: Unexpected identifier 'frameEl' (at luci.js?v=git-23.038.47117-2234d0c:155:3)
  in http://192.168.1.1/luci-static/resources/ui.js?v=git-23.038.47117-2234d0c:?
  at luci.js?v=git-23.038.47117-2234d0c:179:29
    at Object.raise (luci.js?v=git-23.038.47117-2234d0c:155:3)
    at luci.js?v=git-23.038.47117-2234d0c:179:29
raise @ luci.js?v=git-23.038.47117-2234d0c:155
(anonymous) @ luci.js?v=git-23.038.47117-2234d0c:179
Promise.then (async)
(anonymous) @ (index):58
luci.js?v=git-23.038.47117-2234d0c:155 Uncaught (in promise) SyntaxError: Unexpected identifier 'frameEl' (at luci.js?v=git-23.038.47117-2234d0c:155:3)
  in http://192.168.1.1/luci-static/resources/ui.js?v=git-23.038.47117-2234d0c:?
  at luci.js?v=git-23.038.47117-2234d0c:179:29
    at Object.raise (luci.js?v=git-23.038.47117-2234d0c:155:3)
    at luci.js?v=git-23.038.47117-2234d0c:179:29
raise @ luci.js?v=git-23.038.47117-2234d0c:155
(anonymous) @ luci.js?v=git-23.038.47117-2234d0c:179
Promise.then (async)
(anonymous) @ cbi.js?v=git-23.038.32982-f416c27:141
luci.js?v=git-23.038.47117-2234d0c:163 Uncaught (in promise) TypeError: classes.ui.addNotification is not a function
    at error (luci.js?v=git-23.038.47117-2234d0c:163:12)

## Expected behavior:

Use luci to manage openwrt router.

## Additional Information:
Using latest snapshot: luci master (git-23.009.82915-ec3aac4) / [OpenWrt SNAPSHOT r22004-047fb7c76d](https://downloads.openwrt.org/snapshots/targets/ipq40xx/generic/openwrt-ipq40xx-generic-asus_rt-ac42u-squashfs-sysupgrade.bin)
Kernel: [5.15.91-1-53b01a19f22d17f382ee562a60262f97]

OpenWrt version information from system `/etc/openwrt_release`

DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r22004-047fb7c76d'
DISTRIB_TARGET='ipq40xx/generic'
DISTRIB_ARCH='arm_cortex-a7_neon-vfpv4'
DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r22004-047fb7c76d'
DISTRIB_TAINTS=''

This is the log of installing luci after the first boot:

BusyBox v1.36.0 (2023-02-07 15:27:02 UTC) built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt SNAPSHOT, r22004-047fb7c76d
 -----------------------------------------------------
=== WARNING! =====================================
There is no root password defined on this device!
Use the "passwd" command to set up a new password
in order to prevent unauthorized SSH logins.
--------------------------------------------------
root@OpenWrt:~# opkg update
Downloading https://downloads.openwrt.org/snapshots/targets/ipq40xx/generic/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading https://downloads.openwrt.org/snapshots/targets/ipq40xx/generic/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/base/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/targets/ipq40xx/generic/kmods/5.15.91-1-53b01a19f22d17f382ee562a60262f97/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_kmods
Downloading https://downloads.openwrt.org/snapshots/targets/ipq40xx/generic/kmods/5.15.91-1-53b01a19f22d17f382ee562a60262f97/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/luci/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/routing/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/telephony/Packages.sig
Signature check passed.
root@OpenWrt:~# opkg install luci
Installing luci (git-23.024.33244-34dee82) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/luci/luci_git-23.024.33244-34dee82_all.ipk
Installing luci-proto-ipv6 (git-21.148.48881-79947af) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/luci/luci-proto-ipv6_git-21.148.48881-79947af_all.ipk
Installing luci-app-firewall (git-23.035.45612-c54efde) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/luci/luci-app-firewall_git-23.035.45612-c54efde_all.ipk
Installing rpcd (2023-01-21-c0df2a7a-2) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/base/rpcd_2023-01-21-c0df2a7a-2_arm_cortex-a7_neon-vfpv4.ipk
Installing rpcd-mod-file (2023-01-21-c0df2a7a-2) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/base/rpcd-mod-file_2023-01-21-c0df2a7a-2_arm_cortex-a7_neon-vfpv4.ipk
Installing rpcd-mod-luci (20230123-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/luci/rpcd-mod-luci_20230123-1_arm_cortex-a7_neon-vfpv4.ipk
Installing rpcd-mod-ucode (2023-01-21-c0df2a7a-2) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/base/rpcd-mod-ucode_2023-01-21-c0df2a7a-2_arm_cortex-a7_neon-vfpv4.ipk
Installing cgi-io (2022-08-10-901b0f04-21) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/packages/cgi-io_2022-08-10-901b0f04-21_arm_cortex-a7_neon-vfpv4.ipk
Installing ucode-mod-math (2023-01-23-941d1483-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/base/ucode-mod-math_2023-01-23-941d1483-1_arm_cortex-a7_neon-vfpv4.ipk
Installing ucode-mod-html (1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/luci/ucode-mod-html_1_arm_cortex-a7_neon-vfpv4.ipk
Installing liblucihttp0 (2022-07-08-6e68a106-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/luci/liblucihttp0_2022-07-08-6e68a106-1_arm_cortex-a7_neon-vfpv4.ipk
Installing liblucihttp-ucode (2022-07-08-6e68a106-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/luci/liblucihttp-ucode_2022-07-08-6e68a106-1_arm_cortex-a7_neon-vfpv4.ipk
Installing luci-base (git-23.038.47117-2234d0c) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/luci/luci-base_git-23.038.47117-2234d0c_arm_cortex-a7_neon-vfpv4.ipk
Installing rpcd-mod-iwinfo (2023-01-21-c0df2a7a-2) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/base/rpcd-mod-iwinfo_2023-01-21-c0df2a7a-2_arm_cortex-a7_neon-vfpv4.ipk
Installing luci-mod-status (git-23.038.33206-b8f91d5) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/luci/luci-mod-status_git-23.038.33206-b8f91d5_arm_cortex-a7_neon-vfpv4.ipk
Installing luci-mod-system (git-23.013.73089-0186d7e) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/luci/luci-mod-system_git-23.013.73089-0186d7e_all.ipk
Installing luci-mod-network (git-23.038.47117-2234d0c) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/luci/luci-mod-network_git-23.038.47117-2234d0c_all.ipk
Installing luci-mod-admin-full (git-19.253.48496-3f93650) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/luci/luci-mod-admin-full_git-19.253.48496-3f93650_all.ipk
Installing luci-proto-ppp (git-21.158.38888-88b9d84) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/luci/luci-proto-ppp_git-21.158.38888-88b9d84_all.ipk
Installing luci-theme-bootstrap (git-23.038.32982-f416c27) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/luci/luci-theme-bootstrap_git-23.038.32982-f416c27_all.ipk
Installing rpcd-mod-rrdns (20170710) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/luci/rpcd-mod-rrdns_20170710_arm_cortex-a7_neon-vfpv4.ipk
Installing uhttpd (2023-01-28-47561aa1-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/base/uhttpd_2023-01-28-47561aa1-1_arm_cortex-a7_neon-vfpv4.ipk
Installing uhttpd-mod-ubus (2023-01-28-47561aa1-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/base/uhttpd-mod-ubus_2023-01-28-47561aa1-1_arm_cortex-a7_neon-vfpv4.ipk
Installing luci-light (git-23.024.33244-34dee82) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/luci/luci-light_git-23.024.33244-34dee82_all.ipk
Installing rpcd-mod-rpcsys (2023-01-21-c0df2a7a-2) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/base/rpcd-mod-rpcsys_2023-01-21-c0df2a7a-2_arm_cortex-a7_neon-vfpv4.ipk
Installing attendedsysupgrade-common (8) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/packages/attendedsysupgrade-common_8_all.ipk
Installing luci-app-attendedsysupgrade (git-22.285.67526-18bfcca) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/luci/luci-app-attendedsysupgrade_git-22.285.67526-18bfcca_all.ipk
Installing luci-app-opkg (git-23.009.82915-ec3aac4) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/luci/luci-app-opkg_git-23.009.82915-ec3aac4_all.ipk
Configuring liblucihttp0.
Configuring cgi-io.
Configuring luci-app-opkg.
Configuring rpcd.
Configuring rpcd-mod-file.
Configuring rpcd-mod-luci.
Configuring rpcd-mod-ucode.
Configuring ucode-mod-math.
Configuring ucode-mod-html.
Configuring liblucihttp-ucode.
Configuring luci-base.
4+0 records in
4+0 records out
Configuring luci-mod-system.
Configuring luci-theme-bootstrap.
/luci-static/bootstrap
Configuring rpcd-mod-iwinfo.
Configuring luci-mod-status.
Configuring luci-app-firewall.
Configuring luci-proto-ppp.
Configuring luci-mod-network.
Configuring luci-mod-admin-full.
Configuring luci-proto-ipv6.
Configuring rpcd-mod-rpcsys.
Configuring attendedsysupgrade-common.
Configuring luci-app-attendedsysupgrade.
Configuring uhttpd.
4+0 records in
4+0 records out
Configuring rpcd-mod-rrdns.
Configuring uhttpd-mod-ubus.
4+0 records in
4+0 records out
Configuring luci-light.
Configuring luci.
root@OpenWrt:~# /etc/init.d/uhttpd enable
root@OpenWrt:~# /etc/init.d/uhttpd start
4+0 records in
4+0 records out
root@OpenWrt:~#

**Comment by chinabb** [comment] 2023-02-09 02:32
Supplementary information: 
Yesterday, using the same steps to install the previous day’s snapshot version was successful. I want to reinstall it today, but this error occurred. I have repeatedly flashed the firmware many times, and used the firstboot and reboot command to restore the factory and then install luci, but the error still occurs.

**Comment by jow-** [comment] 2023-02-09 08:51
Duplicate of #6230

**Closed by jow-** 2023-02-09 08:51 UTC
