### ISSUE TITLE
Luci chooses WPA3

### ISSUE THREAD

**Issue by castillofrancodamian** [openwrt/luci#4524] opened 2020-10-17 21:42 UTC
When I try to connect to a network when I use the network browser even though it does not use WPA3, it always chooses it.
Use snapshots.

**Comment by ptpt52** [comment] 2020-10-31 17:03
yes, I notice this issue, maybe it is a bug.
ping @Ansuel @jow-

**Comment by Ansuel** [comment] 2020-10-31 18:33
@castillofrancodamian can you post a screenshot or a gif of the problem?

**Comment by ptpt52** [comment] 2020-10-31 19:02
Scan wifi and try to connect to somewhat ssid (and it is WPA2), but the default config is set to WPA3.

I have to change from WPA3 to WPA2 manually

**Comment by castillofrancodamian** [comment] 2020-10-31 22:15
> Scan wifi and try to connect to somewhat ssid (and it is WPA2), but the default config is set to WPA3.
> 
> I have to change from WPA3 to WPA2 manually

That's what I meant, and I can't get a screenshot.

**Comment by Ansuel** [comment] 2020-10-31 22:17
i would have preferred a screenshot but fin i will try to reproduce a push a fix for this.

**Comment by castillofrancodamian** [comment] 2020-10-31 23:50
> i would have preferred a screenshot but fine i will try to reproduce and push a fix for this.

It is easy to reproduce. Following the logic of connecting from the search engine, it can be observed.

**Comment by Ansuel** [comment] 2020-10-31 23:53
@castillofrancodamian can you tell me if your case with what is saved by default if you don't modify the encryption?
I reproduced the bug but it looks like the bug is not really the fact that it wrongly show wpa3 instead of the right one but the fact that it doesn't recognize the right encryption at all and save the first one (in my case luci set the connection with owe with a connection that should be wpa2)

**Comment by castillofrancodamian** [comment] 2020-11-01 00:14
@Ansuel At no point did I say that it does not show the correct encryption, but that it always chooses WPA3 even if the network to connect does not use that encryption and I have to manually change the corresponding one.

**Comment by Ansuel** [comment] 2020-11-01 00:18
You are saying the same thing in different words...
I'm saying that luci wrongly set the wrong encryption.
You are saying that luci by default show wpa3 and you need to change that manually.

If you don't change wpa3 manually luci gen a conf with sae set ahahha
Anyway i think i have fixed this and i will push a fix after some test

**Comment by castillofrancodamian** [comment] 2020-11-01 00:20
@Ansuel Maybe I have used the same words because I am using Google Translator. What I mean is that it does not show or choose the encryption in LuCI correctly.

**Comment by Ansuel** [comment] 2020-11-01 00:21
I mean that we are saying the same thing. Anyway found the problem will be fixed as soon as jow merge the fix I will push ;)
Thx a lot for the report

**Comment by castillofrancodamian** [comment] 2020-11-01 00:22
@Ansuel Thanks for giving me attention! 😊😊😊

**Closed** 2020-11-01 16:23 UTC
