### ISSUE TITLE
luci_git package is missing

### ISSUE THREAD

**Issue by achim71** [openwrt/luci#4934] opened 2021-03-19 15:04 UTC
Seems luci_git ... ipkg got lost.
I tried to install luci on an 19.07.7 build (made with imagebuilder for Netgare R7800) via opkg and got an package luci not found response.
I'd expect the luci_git package here
https://downloads.openwrt.org/releases/19.07.0/packages/arm_cortex-a15_neon-vfpv4/luci/

Fixed it temporary by using an older luci_git package from 19.07.3 from my local download cache.

**Comment by jow-** [comment] 2021-03-19 15:06
Duplicate of #4927 - this is a buildbot issue on the OpenWrt side. I backported buildroot fixes that should address it, but it'll take a few days for the changes to propagate.

**Closed by jow-** 2021-03-19 15:06 UTC

**Comment by achim71** [comment] 2021-03-20 08:46
Thank you for the background information.
The latest build attemt this morning also failed. https://downloads.openwrt.org/releases/faillogs-19.07/arm_cortex-a15_neon-vfpv4/luci/luci/compile.txt
