### ISSUE TITLE
Luci doesn't show available packages that opkg does

### ISSUE THREAD

**Issue by mmaney** [openwrt/luci#5384] opened 2021-09-23 18:48 UTC
Ran into this while reinstalling the handful of packages needed to support P910 with a USB connected printer.  Neither before nor since they've been installed can Luci find them in the list of available packages, though it DOES display them in the installed packages list.  For example, I had to use uci to install this one:
```
root@airport:~# opkg list kmod-usb-printer
kmod-usb-printer - 5.4.143-1 - Kernel support for USB printers
root@airport:~# opkg status kmod-usb-printer
Package: kmod-usb-printer
Version: 5.4.143-1
Depends: kernel (= 5.4.143-1-79c5dc6db69102eb2943a96b9bec8b63), kmod-usb-core
Status: install user installed
Architecture: mips_24kc
Installed-Time: 1632417260
```
An excerpt from Luci's list (I had the thought that perhaps it was just its search, but page 28 of the list also looks like there's lots missing):
```
kmod-usb-hid	5.4.143-1	16.3 KB	Kernel support for USB HID devices such as keyboards and mice
kmod-usb-hid-cp2112	5.4.143-1	10.1 KB	HID device driver which registers as an i2c adapter and gpiochip to expose…	
knot	3.1.0-1	440.6 KB	High-performance authoritative-only DNS server.	
```
I suspect there might be a few other kmods past those two HID items... as opkg list agrees, with ledtrig-usbport, lib-composite, ... yealink.

I also recall that Luci claimed there was no librt package available when I tried to install usbutils.  There again, opkg installed it without a problem, Luci displays it in the installed list but not the available list.

This is on an Archer C5 v7 with OpenWrt 21.02.0.

**Comment by jow-** [comment] 2021-09-23 20:01
Dupe of #5382, #5342, https://bugs.openwrt.org/index.php?do=details&task_id=4006 etc.

In short, the issue is not in LuCI but in the `cgi-io` helper package which should have been fixed with https://github.com/openwrt/packages/commit/aff981470fdcea29989bb5eb59e88cee4343f38e

An `opkg update; opkg upgrade cgi-io` or updating `cgi-io` via LuCI should solve these issues.

**Closed by jow-** 2021-09-23 20:01 UTC
