### ISSUE TITLE
cbi.js ip6addr validation does not correctly handle ipv6 masks

### ISSUE THREAD

**Issue by Flameeyes** [openwrt/luci#816] opened 2016-10-04 23:01 UTC
See https://github.com/openwrt/luci/blob/6a11f71758e151d85eaf1bb611808f2420717ef7/modules/luci-base/htdocs/luci-static/resources/cbi.js#L73

The problem manifests itself while trying to use the trick described in http://blog.dupondje.be/?p=17 to allow dynamic prefix filtering: `::1234:1234:1234:1234/::ffff:ffff:ffff:ffff` is a valid ip6addr (at least for what ip6tables cares) and so it should be accepted, but it is not.

**Comment by cshoredaniel** [comment] 2016-12-10 00:59
@Flameeyes does this work with openwrt firewall program, or does it too need modifications?  That is if you manually edit /etc/config/firewall as mentioned above, does it work?

**Comment by cshoredaniel** [comment] 2016-12-10 01:05
Duplicate of #788

**Closed by cshoredaniel** 2016-12-10 01:05 UTC
Labels: C: LuCI Applications, P: minor, R: duplicate, T: enhancement
