### ISSUE TITLE
New Installed Packages Aren't Seen As Been Installed Until After Reboot

### ISSUE THREAD

**Issue by firewire10000** [openwrt/luci#4096] opened 2020-05-24 18:59 UTC
Whilst I've been flashing v19.07.3 the last couple of days I've noticed when installing packages via the LuCI OPKG manager, after a package has been installed and then switching to the `Installed` tab, it doesn't show as being installed if I enter the exact name of the package into the `Filter:` box.

However, after doing a reboot the `Installed` tab now shows the installed package. I didn't have this on v19.07.2 that I flashed on my Linksys WRT1900ACSv2 last week.

**Comment by jow-** [comment] 2020-05-24 20:00
Dupe of #4077

**Comment by jow-** [comment] 2020-05-24 20:11
Cannot reproduce that issue. Here's a screen capture of my test: http://mein.io/opkg-install-2020-05-24_22.07.56.mp4

**Closed by jow-** 2020-05-24 20:11 UTC
