### ISSUE TITLE
unsaved changes: 0

### ISSUE THREAD

**Issue by bol-van** [openwrt/luci#856] opened 2016-11-19 13:19 UTC
Whatever I change, save but not apply - subj is in the right-top corner.
Changes can be seen in /tmp/.uci
This bug lasts for years

**Comment by cshoredaniel** [comment] 2016-12-09 22:23
@bol-van Can you confirm the version of openwrt and LuCI for which this occurs?

**Comment by cshoredaniel** [comment] 2016-12-09 22:24
@bol-van Also what theme are you using?

**Comment by bol-van** [comment] 2016-12-10 08:00
git-16.306.57050-d7d9772-1
theme - openwrt
looks like bootstrap theme  does not have this indication
and thats why nobody cares because openwrt theme is abandoned

**Comment by jow-** [comment] 2016-12-10 11:04
I cannot reproduce that issue with either Bootstrap or OpenWrt themes.
![changes openwrt](https://cloud.githubusercontent.com/assets/2528802/21072894/d725f590-bed0-11e6-87e5-20531080f2d8.png)
![changes bootstrap](https://cloud.githubusercontent.com/assets/2528802/21072895/d7280696-bed0-11e6-8228-d39a3947b373.png)

**Comment by cshoredaniel** [comment] 2016-12-10 11:50
@bol-van Do you have any custom modifications?  Out of memory? What device? Are you using a snapshot? From where? Did you build your own?  From what repos, and what versions?

**Comment by bol-van** [comment] 2016-12-10 12:01
Custom modifications : no, i didnt modify luci
Out of memory : cant be. it happens even on 1gb ram device.
What device : wndr3800, wndr3700, dir825b2, banana pi. All either run DD or LEDE.
Own firmware : yes, i always build my own, never use snapshots.
What repos : standard git checkout of latest DD/lede

**Comment by bol-van** [comment] 2016-12-10 12:23
Experiment.
I setup LEDE in vmware.
Installed luci there. Works.
Copied /usr/lib/lua/luci from problematic system to vmware lede. Replaced 3 .so inside to x64 version.
It works !

**Comment by cshoredaniel** [comment] 2016-12-10 15:57
That's some sort of compilation issue then (unclean tree?)  Closing 'not a luci bug'

**Closed by cshoredaniel** 2016-12-10 15:57 UTC
Labels: C: LuCI Themes, R: not a luci bug, R: worksforme, T: defect

**Comment by bol-van** [comment] 2016-12-12 10:27
I traced the reason to libuci.so.
(file.c) uci_list_config_files enumerates all files in /etc/config including directories
if directory is found then get_filename returns null
configs[i] remains unset and in most cases contain NULL
all part of code that use config enumeration stop on first NULL
If a directory exist in /etc/config then all fails

```
	char **configs = NULL;
	char **p;
	if ((uci_list_configs(ctx, &configs) != UCI_OK) || !configs) {
		cli_perror();
		goto out;
	}

	for (p = configs; *p; p++) {
		package_cmd(cmd, *p);
	}

```

**Comment by bol-van** [comment] 2016-12-12 10:49
This patch to file.c fixes the problem
```

838c838
<       int size, i;
---
>       int size, i, j;
862c862
<       for(i = 0; i < globbuf.gl_pathc; i++) {
---
>       for(i = 0, j = 0; i < globbuf.gl_pathc; i++) {
872c872
<               configs[i] = buf;
---
>               configs[j++] = buf;


```

**Comment by jow-** [comment] 2016-12-12 10:54
Thanks for figuring this out @bol-van . This has been recently patched upstream in uci.git, see http://git.lede-project.org/49ec6ef .

**Comment by cshoredaniel** [comment] 2016-12-13 14:05
Yes thank you @bol-van I obviously misdiagnosed; thanks @jow-
