### ISSUE TITLE
When the Active Connections is very high, click the connection and there will be a bug that luci cannot log in

### ISSUE THREAD

**Issue by dongc123** [openwrt/luci#6485] opened 2023-07-28 08:49 UTC
When the Active Connections is too high, clicking Connections will result in an error, and repeated logins and clicking Connections will result in a BUG with an incorrect account password. You can only restart openwrt to return to normal. Through this website, you can simulate that the number of active connections is too high to repro
![微信截图_20230726190842](https://github.com/openwrt/luci/assets/109882914/5d2ca544-da1f-4c46-b550-16a296a1acc2)
![微信图片编辑_20230726192225](https://github.com/openwrt/luci/assets/109882914/581adc52-b1d7-42d1-88c5-8ade42f93816)
![微信图片编辑_20230726192405](https://github.com/openwrt/luci/assets/109882914/7f5c392c-341d-4bc0-87d4-05dc60bcaf70)
![微信图片编辑_20230726192632](https://github.com/openwrt/luci/assets/109882914/dd54bac0-a054-4cf3-8a8b-d4aa5a4d5eee)
duce the BUG. https://qps.itzmx.com/

**Comment by jow-** [comment] 2023-07-28 08:58
Duplicate of https://github.com/openwrt/luci/issues/6360

**Closed by jow-** 2023-07-28 08:58 UTC
