### ISSUE TITLE
Host Showing IPV6 Address or ? Mark / Intermittent IPV4 Address

### ISSUE THREAD

**Issue by manjotsc** [openwrt/luci#4848] opened 2021-02-28 05:50 UTC
Hi,

Setup the router as Access Point and connect devices using WiFi. Then go under Network → Wireless then look under HOST there will be a IPV6 address or a question mark. I would like to see a IPV4 address under HOST

- R7800, R6850
- OpenWrt 19.07.7 r11306-c4a6851c72, OpenWrt 21.02-SNAPSHOT r15863-3

https://forum.openwrt.org/t/host-showing-ipv6-address/89804/19

![Screenshot 2021-02-27 232857](https://user-images.githubusercontent.com/51430971/109409228-e9b87a00-795e-11eb-9a6b-5426cb3cae25.png)

**Comment by prateekrastogi** [comment] 2021-03-01 01:22
Goodluck if you can disconnect link PPP of WAN, not showing under any UI using IPv4 bridge 0.0.0.0 despite all Packets being Port Forwarded to of Public IPv6 Internet Addresses dual pair.

**Comment by jow-** [comment] 2021-03-01 07:49
Not a bug. In pure AP mode, the device is not involved in layer 3 routing, hence no details about used IPs or hostnames. Wontfix.

**Closed by jow-** 2021-03-01 07:49 UTC
