### ISSUE TITLE
LEDE   URL stok is Lost ？？？

### ISSUE THREAD

**Issue by zimiao815** [openwrt/luci#3089] opened 2019-09-21 05:06 UTC
Hello everyone

CC15.05:   http://xxxxxxx/cgi-bin/luci/;stok=30414a865205088b2c96cbd97018c4f8/admin/status/overview

LEDE17.01.5:    http://xxxxxxxx/cgi-bin/luci/admin/status/overview

How did it disappear  ???stok=***?

How to modify it to appear？？
Thanks very much！！！

**Comment by hnyman** [comment] 2019-09-21 07:00
> How did it disappear ???stok=***?

It was an intentional change for the whole logging & authentication infra in LuCI.

> How to modify it to appear？？

In theory, by reverting the 30-40 commits in 2015 that made the change, and then modifying the other later source code changes accordingly. 
Some of those changes: https://github.com/openwrt/luci/search?q=token&unscoped_q=token&type=Commits

In practice, no way to revert it.


Not a bug, so I close this.

**Closed by hnyman** 2019-09-21 07:00 UTC
