### ISSUE TITLE
Option "802.11w Management Frame Protection" in OpenWrt 21.02 on Linksys EA4500 (kirkwood)

### ISSUE THREAD

**Issue by duc5800** [openwrt/luci#5431] opened 2021-10-10 19:36 UTC
Via the menu "Network -> Wireless", then clicking the "Edit" button for one of the radios and then "Interface Configuration -> Wireless Security" I can set the state of "802.11w Management Frame Protection" to either "Disabled", "Optional" or "Required".
Selecting "Required" adds the line "option ieee80211w '2'" to the applicable section of /etc/config/wireless.
Selecting "Optional" adds the line "option ieee80211w '1'" to the applicable section of /etc/config/wireless.
Selecting "Disabled" removes the line "option ieee80211w" from the applicable section of /etc/config/wireless.

However, it appears that with the line "option ieee80211w" missing from the wireless config file the driver actually defaults to the "Optional" state. 
In order to disable 802.11w I have to manually edit the file /etc/config/wireless and add the line "option ieee80211w '0'" to the applicable section.

After doing this the dropdown menu for "802.11w Management Frame Protection" in LuCi will show the state as "Disabled".

**Comment by jow-** [comment] 2021-10-10 19:45
Duplicate of #5394

**Closed** 2021-10-10 19:46 UTC
