### ISSUE TITLE
luci-app-shadowsocks-libev How can I set the ipt_args option, thank you

### ISSUE THREAD

**Issue by vbzc** [openwrt/luci#3132] opened 2019-09-30 13:41 UTC
How can I set the ipt_args option

I want to use this function to set the port of the proxy. I tried a lot of writing methods and it is not successful. Please tell me how to set it in luci, thank you.

**Comment by jow-** [comment] 2019-09-30 14:15
Duplicate of #3129

**Closed by jow-** 2019-09-30 14:15 UTC
Labels: help wanted
