### ISSUE TITLE
Scheduled Tasks: remove all entries

### ISSUE THREAD

**Issue by maxschaf** [openwrt/luci#609] opened 2015-12-22 11:36 UTC
It is not possible to clear the textarea and save. After saving, the previously entered text appears again. The textarea needs to contain at least one char to be saved.

Powered by LuCI (git-15.051.48491-4137afe)

**Comment by hnyman** [comment] 2016-03-12 09:32
Closing this as a duplicate of #668 
There is more discussion about the same issue.

**Closed by hnyman** 2016-03-12 09:32 UTC
