### ISSUE TITLE
[luci-app-openvpn] Can't add new instance of OpenVPN config

### ISSUE THREAD

**Issue by Scvairy** [openwrt/luci#1237] opened 2017-07-19 08:10 UTC
The only instance, which you can see on screenshot, i have made from uci.

luci-app-openvpn | git-17.194.52964-580f012-1
![image](https://user-images.githubusercontent.com/8327460/28356744-97da5344-6c82-11e7-8cd7-7ea024a9f289.png)

**Comment by Wedmer** [comment] 2017-08-29 10:08
Can't reproduce. Please write your steps to get this problem.

**Comment by dibdot** [comment] 2018-09-16 15:34
Fixed with 1eb3f73

**Closed by dibdot** 2018-09-16 15:34 UTC
