### ISSUE TITLE
Openwrt 21-20-rc3 openvpn Insufficient permissions to read UCI configuration.

### ISSUE THREAD

**Issue by predators46** [openwrt/luci#5209] opened 2021-07-25 02:56 UTC
![Screenshot_2021-07-25_105137](https://user-images.githubusercontent.com/31931530/126886151-bb7850fa-3ece-4811-a55b-80c194ee9948.jpg)

**Comment by dibdot** [comment] 2021-07-25 15:31
Duplicate of #4370

**Closed by dibdot** 2021-07-25 15:31 UTC
