### ISSUE TITLE
luci-mod-network: Mesh mode appears even when there is no support

### ISSUE THREAD

**Issue by howl** [openwrt/luci#5823] opened 2022-05-21 14:33 UTC
Is possible to select mode 802.11s in WiFi network settings even if wpad-basic is installed. It should be checked if 802.11s is possible not by the device only but first by wpad.

**Comment by castillofrancodamian** [comment] 2022-05-21 19:41
It even shows the WPS option and I don't think it supports 802.11s.

**Comment by jow-** [comment] 2022-06-06 22:43
Dupe of #2628

**Closed by jow-** 2022-06-06 22:43 UTC
