### ISSUE TITLE
DHCP crash beacause insufficient regexp checks

### ISSUE THREAD

**Issue by RuderLaplace** [openwrt/luci#1661] opened 2018-03-04 10:27 UTC
In firm 15.363.78009-956be55, the web form allows to enter a reserved static ip hostname with a character "_" at the begining of the name. Tought whenever it restart the service crashes due to this.

**Comment by dibdot** [comment] 2018-03-05 18:31
15.363 looks like an ancient, home brewed chaos calmer release ... did you retest with a current snapshot or latest stable release 17.01.x series?

**Comment by RuderLaplace** [comment] 2018-03-17 23:38
17.01.4 r3560-79f57e422d
Same problem.
Sun Mar 18 00:33:31 2018 daemon.crit dnsmasq[1098]: bad DHCP host name at line 27 of /var/etc/dnsmasq.conf.cfg02411c
Sun Mar 18 00:33:31 2018 daemon.crit dnsmasq[1098]: FAILED to start up

**Comment by dibdot** [comment] 2018-03-18 07:25
@RuderLaplace Thanks for re-testing!

I can confirm that this still exists in current trunk. Root cause is the used "hostname" dataytpe for validation, which allows an underscore at the beginning.

@jow- @hnyman Should we add an additional datatype "dhcphost" which does not allow an "_" at the beginning or should we fix this only in dhcp.lua or maybe a totally different approach?

**Comment by RuderLaplace** [comment] 2018-03-18 18:59
Doing a bit of research, I found out the RCF syntaxis:
* grep regexp:  "^[a-zA-Z]\([a-zA-Z0-9\-]*[a-zA-Z0-9]\)*$"
* Description: «[...] They must start with a letter, end with a letter or digit, and have as interior characters only letters, digits, and hyphen.
 [...] Labels must be 63 characters or less.»
* Syntaxis:
<domain> ::= <subdomain> | " "
<subdomain> ::= <label> | <subdomain> "." <label>
<label> ::= <letter> [ [ <ldh-str> ] <let-dig> ]
<ldh-str> ::= <let-dig-hyp> | <let-dig-hyp> <ldh-str>
<let-dig-hyp> ::= <let-dig> | "-"
<let-dig> ::= <letter> | <digit>
<letter> ::= any one of the 52 alphabetic characters A through Z in upper case and a through z in lower case
<digit> ::= any one of the ten digits 0 through 9

*Ref: https://tools.ietf.org/html/rfc1034#section-3.5

You're welcome ;)

**Comment by dibdot** [comment] 2018-04-07 15:55
Fixed with 94ea907 and 70ffbe6

**Closed by dibdot** 2018-04-07 15:55 UTC
