### ISSUE TITLE
rc.local lost saved scripts

### ISSUE THREAD

**Issue by henok400** [openwrt/luci#2977] opened 2019-08-11 06:19 UTC
Openwrt v18.06.4 is luci system -> startup app  start and stop the saved rc.local script erased 
Please Developer fix this bugs in openwrt

**Comment by jow-** [comment] 2019-08-26 07:11
Dupe of #2760 - should be fixed by 7995ef34b5de544a05af9b3aa77c88a5304e6968

**Closed by jow-** 2019-08-26 07:11 UTC
