### ISSUE TITLE
Menu Header always present on latest snapshots

### ISSUE THREAD

**Issue by AndyX90** [openwrt/luci#3785] opened 2020-03-26 11:29 UTC
Hey guys, on latest snapshots is a bug that the menu-header is shown on login page, even if no user is logged in.
![Unbenannt](https://user-images.githubusercontent.com/10565317/77641975-329ccd00-6f5d-11ea-84e7-bd69ee0e43f7.png)
Here is the latest working version i have:
![Unbenannt1](https://user-images.githubusercontent.com/10565317/77642011-42b4ac80-6f5d-11ea-9771-93494efdfb7f.png)

**Comment by jow-** [comment] 2020-03-26 11:33
Dupe of #3653

**Closed by jow-** 2020-03-26 11:33 UTC
