### ISSUE TITLE
Set password button not shown

### ISSUE THREAD

**Issue by jjm2473** [openwrt/luci#5747] opened 2022-03-27 16:19 UTC
`dispatcher.lookup` only lookup lua defined node.

so `dispatcher.lookup("admin/system/admin")` will always return false.

https://github.com/openwrt/luci/blob/d9ffe119858e80b051d0e4dd86615bba0341edd2/themes/luci-theme-bootstrap/luasrc/view/themes/bootstrap/header.htm#L71-L73

not only bootstrap, but all themes will not shown "Go to password configuration..." button.

**Comment by jjm2473** [comment] 2022-03-27 16:20
affacts luci/opnewrt-21 and up.

**Comment by jow-** [comment] 2022-03-29 14:32
Dupe of #5202

**Closed by jow-** 2022-03-29 14:32 UTC
