### ISSUE TITLE
luci-mod-network: MAC format validity check missing in "Network → DHCP and DNS → Static leases" section

### ISSUE THREAD

**Issue by senca23** [openwrt/luci#6955] opened 2024-03-02 15:21 UTC
## Steps to reproduce:

1. go to: Network → DHCP and DNS → Static leases
2. Add a new lease and enter an invalid MAC address for host
3. Save & Apply

## Actual behavior:
Invalid MAC address gets passed to config file "/etc/config/dhcp".

## Expected behavior:
Luci should reject the invalid mac user input and warn the user.

## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`

```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='23.05.2'
DISTRIB_REVISION='r23630-842932a63d'
DISTRIB_TARGET='ipq807x/generic'
DISTRIB_ARCH='aarch64_cortex-a53'
DISTRIB_DESCRIPTION='OpenWrt 23.05.2 r23630-842932a63d'
DISTRIB_TAINTS=''
```

Example:
![Screenshot_2024-03-02_14-30-27](https://github.com/openwrt/luci/assets/142660118/772409aa-4aad-445f-97a7-f773109e48a4)
![Screenshot_2024-03-02_14-25-39](https://github.com/openwrt/luci/assets/142660118/56b1101a-a1e3-4fa9-99d2-3a5a8633b250)

**Comment by dannil** [comment] 2024-03-03 10:20
This got fixed by https://github.com/openwrt/luci/commit/bcaa445f088ad901da693a29b55e80295cb8f093 but isn't in the 23.05 branch. I can't reproduce it on latest `master`.

![Screenshot_31](https://github.com/openwrt/luci/assets/7290072/16d8358b-362c-44d7-ab5a-3b26b373e399)

**Closed as completed** 2024-03-03 12:26 UTC
