### ISSUE TITLE
Missing SLAAC/RA announced DNS configuration support

### ISSUE THREAD

**Issue by SvenKiljan** [openwrt/luci#5600] opened 2021-12-14 10:58 UTC
In OpenWRT 19.x, the 'Announced DNS servers' and Announced DNS domains options were always available in an interface's DHCP Server IPv6 Settings., even when DHCPv6 was disabled. This was a feature, not a bug. [SLAAC/RA can announce DNS configuration](https://datatracker.ietf.org/doc/html/rfc8106), which is especially useful in environments where DHCPv6 usage is undesirable or unnecessary.

**Current situation**
In OpenWRT 21.x, the 'Announced IPv6 DNS servers' and 'Announced DNS domains' options are only available if DHCPv6-Service is either in server mode or hybrid mode.

**Desired situation**
The 'Announced IPv6 DNS servers' and 'Announced DNS domains' options should also be available if RA-Service is in server mode or hybrid mode, even if DHCPv6-Service is disabled or in relay mode.

**Workaround**
If RA-Service is either in server mode or hybrid mode and DHCPv6-service is disabled (or in relay mode), run the following commands through SSH:
```
uci add_list dhcp.<interface>.dns='<IPv6 address>'
uci add_list dhcp.<interface>.domain='<domain name>'
uci commit dhcp
```

Replace &lt;interface> with the interface name, &lt;IPv6 address> with the address of an IPv6 DNS server, and &lt;domain name> with a domain to announce. Repeat the first command for every IPv6 server to announce, and the second for every domain to announce.

This will not be visible in the web-interface (unless one temporarily enables DHCPv6-Service in either server or hybrid mode), but it does work. The DNS configuration will be announced through SLAAC (or through 'RA'/'Router Advertisement', whichever term is preferred).

**Comment by jow-** [comment] 2021-12-14 15:51
Duplicate of  #5564

**Closed by jow-** 2021-12-14 15:51 UTC
