### ISSUE TITLE
Feature Request: enable random mac address function in LuCI

### ISSUE THREAD

**Issue by Che15ea** [openwrt/luci#5819] opened 2022-05-20 16:37 UTC
Feature Request:
I think we need a random/stable/specify Mac address spoofing function in LuCI as wifi/ethernet server/client to protect against mac address tracking. The feature is already built in most linux distros.

**Comment by jow-** [comment] 2022-05-20 17:26
Duplicate of #5819

**Comment by jow-** [comment] 2022-05-20 17:27
Correction. Duplicate of #5517

**Closed by jow-** 2022-05-20 17:27 UTC

**Comment by Neustradamus** [comment] 2025-01-12 01:33
Linked to:
- https://github.com/openwrt/luci/issues/5517
- https://github.com/openwrt/luci/issues/5819
- https://github.com/openwrt/luci/issues/5845
- https://github.com/openwrt/luci/pull/5896
- https://github.com/openwrt/luci/issues/7131
