### ISSUE TITLE
luci-mod-network: wan_6 error editing

### ISSUE THREAD

**Issue by timur-davletshin** [openwrt/luci#6602] opened 2023-09-28 16:09 UTC
```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='23.05.0-rc3'
DISTRIB_TARGET='x86/64'
DISTRIB_ARCH='x86_64'
```

If IPv6 is configured via `option ipv6 'auto'` (OpenWrt creates interface `wan_6` dynamically) edit button should be disabled or it produced non-sensical error `TypeError sref is null`

![luci-mod-network](https://github.com/openwrt/luci/assets/143790409/27386c20-9c9b-486a-9d93-2048df09df16)

**Comment by jow-** [comment] 2023-09-28 21:33
Duplicate of #6229

**Closed by jow-** 2023-09-28 21:33 UTC
