### ISSUE TITLE
Wireless overview page / list of associated stations misses dynamic vlan devices

### ISSUE THREAD

**Issue by NerdyProjects** [openwrt/luci#3645] opened 2020-02-18 10:37 UTC
Clients connected to a wifi with dynamic VLAN (e.g. wpa enterprise with radius assigned vlans) do not get shown in the list of associated stations or are taken into account when general stats for a wifi device are displayed (e.g. on the main status page but also on the wireless page).

Devices that are connected to the wifi without getting a vlan assigned are properly shown.

When a client connects, another wifi device gets created (e.g. `wlan0.100` for VLAN id 100), `iwinfo` also displays information to that.

I don't understand the complexity in luci good enough. In `modules/luci-compat/luasrc/model/network.lua` is a lot of related stuff, it looks like it is iterated/filtered by the networks in the uci config and therefore loses the information about the vlans. But that is more a guess.

Related #1324

**Comment by jow-** [comment] 2020-02-18 10:38
Duplicate of #1324

**Closed by jow-** 2020-02-18 10:38 UTC
