### ISSUE TITLE
luci seems to be corrupt, unable to find section 'main'

### ISSUE THREAD

**Issue by datenleck** [openwrt/luci#5338] opened 2021-09-06 10:29 UTC
Hi,

just updated from 19.07.8 to 21.02.0.

And I get this:
/usr/lib/lua/luci/dispatcher.lua:427: /etc/config/luci seems to be corrupt, unable to find section 'main'

See: #4758

**Comment by jow-** [comment] 2021-09-06 20:25
Duplicate of #4758

**Closed by jow-** 2021-09-06 20:25 UTC
